ARG IMAGE
FROM $IMAGE
LABEL maintainer="Denis Sventitsky <denis.sventitsky@gmail.com>"

ENV PYTHONUNBUFFERED 1
ENV APP_PATH=/usr/src/todo/
ENV SCRIPTS_PATH=/usr/src/scripts

RUN mkdir -p $APP_PATH
RUN mkdir -p $SCRIPTS_PATH
WORKDIR $APP_PATH

COPY dockerX/todo/systemuser.py $SCRIPTS_PATH
COPY todo/requirements.txt .
RUN pip install -r requirements.txt
COPY todo/ .

CMD python3 manage.py migrate && python3 $SCRIPTS_PATH/systemuser.py && python3 manage.py runserver 0.0.0.0:8000
