# Generated by Django 2.2.3 on 2019-08-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('category', models.CharField(blank=True, choices=[('programming_language', 'Programming Language'), ('database', 'Database'), ('cloud_technology', 'Cloud Technology'), ('testing_tool', 'Testing Tool'), ('frameworks', 'Frameworks'), ('other', 'Other')], db_index=True, default=None, max_length=32, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'verbose_name_plural': 'TaskTag',
                'ordering': ['task'],
                'unique_together': {('task', 'tag')},
            },
        ),
    ]
