# Generated by Django 2.2.3 on 2019-08-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('stopped', 'stopped'), ('failed', 'failed'), ('completed', 'completed')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('path', models.CharField(blank=True, max_length=256, null=True, verbose_name='Path')),
                ('params', models.TextField(null=True, verbose_name='Params')),
                ('msg', models.CharField(blank=True, max_length=256, null=True, verbose_name='msg')),
                ('task_id', models.CharField(max_length=128, null=True, verbose_name='task_id')),
            ],
            options={
                'verbose_name_plural': 'Histories',
                'ordering': ['-id'],
            },
        ),
    ]
